# Generated by Django 6.0.6 on 2026-06-12 05:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('task_efficiency', models.FloatField(default=0)),
                ('task_completed', models.IntegerField(default=0)),
                ('task_total', models.IntegerField(default=0)),
                ('quran_efficiency', models.FloatField(default=0)),
                ('quran_repeats', models.IntegerField(default=0)),
                ('quran_memorized', models.IntegerField(default=0)),
                ('overall_efficiency', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
