# Generated by Django 6.0.6 on 2026-07-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dailyquest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyQuest',
        ),
    ]
