# Generated by Django 6.0.6 on 2026-06-08 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AyahMemorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.IntegerField()),
                ('ayah_number', models.IntegerField()),
                ('is_memorized', models.BooleanField(default=False)),
                ('repeats', models.IntegerField(default=0)),
                ('mushaf_image', models.ImageField(blank=True, null=True, upload_to='mushaf_images/')),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hifz_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['surah_number', 'ayah_number'],
                'unique_together': {('user', 'surah_number', 'ayah_number')},
            },
        ),
    ]
