# Generated by Django 6.0.6 on 2026-06-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayahmemorization',
            name='custom_audio',
            field=models.FileField(blank=True, null=True, upload_to='custom_audios/'),
        ),
        migrations.AddField(
            model_name='ayahmemorization',
            name='custom_audio_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
