# Generated by Django 6.0.6 on 2026-06-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_ayahmemorization_custom_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayahmemorization',
            name='tafsir_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ayahmemorization',
            name='tafsir_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
