# Generated by Django 6.0.6 on 2026-06-06 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prayer', models.CharField(choices=[('bomdod', 'Bomdod'), ('quyosh', 'Quyosh'), ('peshin', 'Peshin'), ('asr', 'Asr'), ('shom', 'Shom'), ('xufton', 'Xufton')], max_length=10)),
                ('time', models.TimeField()),
            ],
            options={
                'ordering': ['date', 'time'],
                'unique_together': {('date', 'prayer')},
            },
        ),
        migrations.CreateModel(
            name='PrayerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prayer', models.CharField(choices=[('bomdod', 'Bomdod'), ('quyosh', 'Quyosh'), ('peshin', 'Peshin'), ('asr', 'Asr'), ('shom', 'Shom'), ('xufton', 'Xufton')], max_length=10)),
                ('is_done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date', 'prayer')},
            },
        ),
    ]
