# Generated by Django 6.0.6 on 2026-06-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibodat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayerlog',
            options={'ordering': ['date', 'prayer']},
        ),
        migrations.AddField(
            model_name='prayerlog',
            name='done_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prayerlog',
            name='status',
            field=models.CharField(choices=[('on_time', 'Vaqtida'), ('late', 'Kechikib'), ('qaza', 'Qaza'), ('missed', "O'tkazib")], default='missed', max_length=10),
        ),
    ]
