# Generated by Django 6.0.6 on 2026-06-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibodat', '0002_alter_prayerlog_options_prayerlog_done_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrayerTime',
        ),
        migrations.AlterField(
            model_name='prayerlog',
            name='prayer',
            field=models.CharField(choices=[('bomdod', 'Bomdod'), ('peshin', 'Peshin'), ('asr', 'Asr'), ('shom', 'Shom'), ('xufton', 'Xufton')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prayerlog',
            name='status',
            field=models.CharField(choices=[('on_time', 'Vaqtida'), ('late', 'Kechikib'), ('makruh', 'Makruh vaqtda'), ('qaza', 'Qazo'), ('pending', 'Kutilmoqda'), ('missed', "O'tkazildi")], default='pending', max_length=10),
        ),
    ]
