# Generated by Django 6.0.6 on 2026-06-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibodat', '0003_delete_prayertime_alter_prayerlog_prayer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerlog',
            name='status',
            field=models.CharField(choices=[('on_time', 'Boshida'), ('late', "O'rtasida"), ('makruh', 'Oxirida'), ('qaza', 'Qazo'), ('missed', "O'tkazib")], default='missed', max_length=10),
        ),
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prayer', models.CharField(choices=[('bomdod', 'Bomdod'), ('peshin', 'Peshin'), ('asr', 'Asr'), ('shom', 'Shom'), ('xufton', 'Xufton')], max_length=10)),
                ('time', models.TimeField()),
            ],
            options={
                'ordering': ['date', 'time'],
                'unique_together': {('date', 'prayer')},
            },
        ),
    ]
