# Generated by Django 6.0.6 on 2026-06-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibodat', '0004_alter_prayerlog_status_prayertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerlog',
            name='status',
            field=models.CharField(choices=[('jamoat', 'Jamoat bilan'), ('on_time', 'Boshida'), ('late', "O'rtasida"), ('makruh', 'Oxirida'), ('qaza', 'Qazo'), ('missed', "O'tkazib")], default='missed', max_length=10),
        ),
    ]
