# Generated by Django 6.0.6 on 2026-06-10 19:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(choices=[('prayer', 'Namoz'), ('task', 'Vazifa'), ('hifz', "Qur'on yodlash"), ('streak', 'Streak saqlash')], max_length=20)),
                ('target_value', models.IntegerField(default=1)),
                ('current_progress', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('failed', 'Bajarilmadi')], default='pending', max_length=20)),
                ('is_auto_generated', models.BooleanField(default=True)),
                ('motivational_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date', 'target_type')},
            },
        ),
    ]
